language: haxe

haxe:
  - development
  - 3.2.1

os:
  - linux
  - osx

sudo: false

install:
  - yes | haxelib install test.hxml

script:
  - haxelib run munit test -result-exit-code -neko
  - haxelib run munit test -result-exit-code -cpp